"""
Entity blueprint backed by the entity database table.
"""

# First party imports
from os.path import basename as os_path_basename
from re import IGNORECASE as re_IGNORECASE
from re import search as re_search

# Library imports
from flask import Blueprint, Response, request
from flask_restful import Resource
from marshmallow import RAISE, ValidationError, fields

# Local imports
from api_server import ma, limiter, get_rate_limit
from configs.api_config import STATUS_CODES
from models import Entity, User, db
from api_server import api
from .blueprints_utils import (
    create_response,
    get_hateos_location_string,
    handle_options_request,
    log,
    jwt_validation_required,
    safe_string,
)

# Define blueprint name constant based on file name
BP_NAME: str = os_path_basename(__file__).replace("_bp.py", "")

# Initialize blueprint object
entity_bp = Blueprint(BP_NAME, __name__)


class EntitySchema(ma.Schema):
    """
    Marshmallow schema for validating and deserializing input data for Entity resources.
    Contains validation rules for each field and specifies that unknown fields in the input should be rejected with an error.
    The ID field is not included since it's auto-generated by the database and should not be provided in input data, providing it in the input will result in a validation error.
    This approach also provides protection against overposting/mass assignment vulnerabilities, ensuring that clients cannot set fields that they are not supposed to.
    """

    class Meta:
        unknown = RAISE  # additional fields in the input will be rejected with an error

    # no field for entity_id since it's auto-generated by the database and should not be provided in input data
    name = fields.String(required=True, validate=safe_string)
    responsible_email = fields.Email(required=True)


# Initialize schema instance for use in resource methods
entity_schema = EntitySchema()


class EntityResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}/<int:id_>"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def get(self, id_, identity) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "id must be positive integer."}, STATUS_CODES["bad_request"]
            )

        entity = Entity.query.get(id_)
        if entity is None:
            return create_response(
                {"error": "no resource found with specified id"},
                STATUS_CODES["not_found"],
            )

        log(
            message=f"User {identity} fetched entity with id {id_}",
            level="INFO",
            message_id="OPRGET",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "entity_id": id_,
            },
        )
        return create_response(entity.to_dict(), STATUS_CODES["ok"])

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def patch(self, id_, identity) -> Response:
        try:
            data = entity_schema.load(request.get_json(), partial=True)
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        entity = Entity.query.get(id_)
        if entity is None:
            return create_response(
                {"error": "no resource found with specified id"},
                STATUS_CODES["not_found"],
            )

        if (
            "responsible_email" in data
            and User.query.filter_by(email=data["responsible_email"]).first() is None
        ):
            return create_response(
                {"error": "specified user does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if "name" in data:
            entity.name = data["name"]
        if "responsible_email" in data:
            entity.responsible_email = data["responsible_email"]

        db.session.commit()
        log(
            message=f"User {identity} updated entity with id {id_}",
            level="INFO",
            message_id="OPRPATCH",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "entity_id": id_,
            },
        )
        return create_response(
            {
                "outcome": "successfully updated entity",
                "location": get_hateos_location_string(bp_name=BP_NAME, id_=id_),
            },
            STATUS_CODES["ok"],
        )

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def delete(self, id_, identity) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "id must be positive integer."}, STATUS_CODES["bad_request"]
            )

        entity = Entity.query.get(id_)
        if entity is None:
            return create_response(
                {"error": "no resource found with specified id"},
                STATUS_CODES["not_found"],
            )

        db.session.delete(entity)
        db.session.commit()
        log(
            message=f"User {identity} deleted entity with id {id_}",
            level="INFO",
            message_id="OPRDEL",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "entity_id": id_,
            },
        )
        return create_response(
            {"outcome": "successfully deleted entity"}, STATUS_CODES["ok"]
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


class EntityPostResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def post(self, identity) -> Response:
        try:
            data = entity_schema.load(request.get_json())
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        if User.query.filter_by(email=data["responsible_email"]).first() is None:
            return create_response(
                {"error": "specified user does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if Entity.query.filter_by(name=data["name"]).first() is not None:
            return create_response(
                {"error": "entity already exists"}, STATUS_CODES["conflict"]
            )

        new_entity = Entity(**data)
        db.session.add(new_entity)
        db.session.commit()

        log(
            message=f"User {identity} created entity with id {new_entity.entity_id}",
            level="INFO",
            message_id="OPRPOST",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "entity_id": new_entity.entity_id,
            },
        )
        return create_response(
            {
                "outcome": "successfully created new entity",
                "location": get_hateos_location_string(
                    bp_name=BP_NAME, id_=new_entity.entity_id
                ),
            },
            STATUS_CODES["created"],
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


# Register resources with the API
api.add_resource(EntityResource, *EntityResource.ENDPOINT_PATHS)
api.add_resource(EntityPostResource, *EntityPostResource.ENDPOINT_PATHS)
