"""
Hydrant blueprint backed by the hydrant database table.
"""

# First party imports
from os.path import basename as os_path_basename
from typing import Any, Dict

# Library imports
from flask import Blueprint, Response, request
from flask_restful import Resource
from marshmallow import EXCLUDE, ValidationError, fields, validate

# Local imports
from api_server import ma, limiter, get_rate_limit
from configs.api_config import STATUS_CODES
from models import Entity, Hydrant, User, db
from api_server import api
from .blueprints_utils import (
    create_response,
    get_hateos_location_string,
    handle_options_request,
    log,
    jwt_validation_required,
    safe_string,
)

# Define blueprint name constant based on file name
BP_NAME: str = os_path_basename(__file__).replace("_bp.py", "")

# Initialize blueprint object
hydrant_bp = Blueprint(BP_NAME, __name__)


class HydrantSchema(ma.Schema):
    """
    Marshmallow schema for validating and deserializing input data for Hydrant resources.
    Contains validation rules for each field and specifies that unknown fields in the input should be rejected with an error.
    The ID field is not included since it's auto-generated by the database and should not be provided in input data, providing it in the input will result in a validation error.
    This approach also provides protection against overposting/mass assignment vulnerabilities, ensuring that clients cannot set fields that they are not supposed to.
    """

    class Meta:
        unknown = RAISE  # additional fields in the input will be rejected with an error

    # no field for hydrant_id since it's auto-generated by the database and should not be provided in input data
    latitude = fields.Float(required=True, validate=validate.Range(min=-90, max=90))
    longitude = fields.Float(required=True, validate=validate.Range(min=-180, max=180))
    address = fields.String(required=True, validate=safe_string)
    status = fields.String(
        load_default="Sconosciuto",
        validate=validate.OneOf(["Nuovo", "Discreto", "Pessimo", "Sconosciuto"]),
    )
    operational = fields.Boolean(load_default=False)
    positioning = fields.String(
        required=True, validate=validate.OneOf(["Soprassuolo", "Sottosuolo"])
    )
    surface = fields.String(
        required=True,
        validate=validate.OneOf(["Asfalto", "Erba", "Terra base pietra", "Altro"]),
    )
    leaks = fields.Boolean(load_default=False)
    has_pit = fields.Boolean(load_default=False)
    truck_access = fields.Boolean(load_default=False)
    maintenance_status = fields.String(
        load_default="Assente",
        validate=validate.OneOf(["Buona", "Discreta", "Assente"]),
    )
    entity_id = fields.Integer(required=True, validate=validate.Range(min=1))


hydrant_schema = HydrantSchema()


class HydrantResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}/<int:id_>"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def get(self, id_, identity) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "id_ must be positive integer"}, STATUS_CODES["bad_request"]
            )

        hydrant = Hydrant.query.get(id_)
        if hydrant is None:
            return create_response(
                {"error": "No data found for the provided ID."},
                STATUS_CODES["not_found"],
            )

        log(
            message=f"User {identity} fetched hydrant with id {id_}",
            level="INFO",
            message_id="HYDGET",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "hydrant_id": id_,
            },
        )
        return create_response(hydrant.to_dict(), STATUS_CODES["ok"])

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def patch(self, id_, identity) -> Response:
        try:
            data = hydrant_schema.load(request.get_json(), partial=True)
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        if id_ <= 0:
            return create_response(
                {"error": "id_ must be positive integer"}, STATUS_CODES["bad_request"]
            )

        hydrant = Hydrant.query.get(id_)
        if hydrant is None:
            return create_response(
                {"error": "specified resource does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if "entity_id" in data and Entity.query.get(data["entity_id"]) is None:
            return create_response(
                {"error": "specified entity does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        user_exists = User.query.filter_by(email=identity).first() is not None
        if not user_exists:
            return create_response(
                {"error": "email found in JWT not present in database"},
                STATUS_CODES["bad_request"],
            )

        for key, value in data.items():
            setattr(hydrant, key, value)

        db.session.commit()
        log(
            message=f"User {identity} updated hydrant with id {id_}",
            level="INFO",
            message_id="HYDPATCH",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "hydrant_id": id_,
            },
        )
        return create_response(
            {
                "outcome": "successfully updated hydrant",
                "location": get_hateos_location_string(bp_name=BP_NAME, id_=id_),
            },
            STATUS_CODES["ok"],
        )

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def delete(self, id_, identity) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "id_ must be positive integer."}, STATUS_CODES["bad_request"]
            )

        hydrant = Hydrant.query.get(id_)
        if hydrant is None:
            return create_response(
                {"error": "specified resource does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        db.session.delete(hydrant)
        db.session.commit()
        log(
            message=f"User {identity} deleted hydrant with id {id_}",
            level="INFO",
            message_id="HYDDEL",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "hydrant_id": id_,
            },
        )
        return create_response(
            {"outcome": "successfully deleted hydrant"}, STATUS_CODES["ok"]
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


class HydrantPostResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def post(self, identity) -> Response:
        try:
            data = hydrant_schema.load(request.get_json())
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        if User.query.filter_by(email=identity).first() is None:
            return create_response(
                {"error": "email found in JWT not present in database"},
                STATUS_CODES["bad_request"],
            )

        if Entity.query.get(data["entity_id"]) is None:
            return create_response(
                {"error": "specified entity does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        new_hydrant = Hydrant(**data)
        db.session.add(new_hydrant)
        db.session.commit()

        log(
            message=f"User {identity} created hydrant with id_ {new_hydrant.hydrant_id}",
            level="INFO",
            message_id="HYDPOST",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "hydrant_id": new_hydrant.hydrant_id,
            },
        )
        return create_response(
            {
                "outcome": "successfully created new hydrant",
                "location": get_hateos_location_string(
                    bp_name=BP_NAME, id_=new_hydrant.hydrant_id
                ),
            },
            STATUS_CODES["created"],
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


api.add_resource(HydrantResource, *HydrantResource.ENDPOINT_PATHS)
api.add_resource(HydrantPostResource, *HydrantPostResource.ENDPOINT_PATHS)
