"""
Maintenance blueprint backed by the maintenance database table.
"""

# First party imports
from os.path import basename as os_path_basename
from typing import Any, Dict

# Library imports
from flask import Blueprint, Response, request
from flask_restful import Resource
from marshmallow import RAISE, ValidationError, fields, validate

# Local imports
from api_server import ma, limiter, get_rate_limit
from configs.api_config import STATUS_CODES
from models import Hydrant, Maintenance, User, db
from api_server import api
from .blueprints_utils import (
    create_response,
    get_hateos_location_string,
    handle_options_request,
    log,
    jwt_validation_required,
    safe_string,
)

# Define blueprint name constant based on file name
BP_NAME: str = os_path_basename(__file__).replace("_bp.py", "")

# Initialize blueprint object
maintenance_bp = Blueprint(BP_NAME, __name__)


class MaintenanceSchema(ma.Schema):
    """
    Marshmallow schema for validating and deserializing input data for Maintenance resources.
    Contains validation rules for each field and specifies that unknown fields in the input should be rejected with an error.
    The ID field is not included since it's auto-generated by the database and should not be provided in input data, providing it in the input will result in a validation error.
    This approach also provides protection against overposting/mass assignment vulnerabilities, ensuring that clients cannot set fields that they are not supposed to.
    """

    class Meta:
        unknown = RAISE  # additional fields in the input will be rejected with an error

    # no field for maintenance_id since it's auto-generated by the database and should not be provided in input data
    hydrant_id = fields.Integer(required=True, validate=validate.Range(min=1))
    user_email = fields.Email(required=True)
    maintenance_timestamp = fields.DateTime(required=True)
    type = fields.String(
        required=True,
        validate=validate.OneOf(
            [
                "Controllo periodico di manutenzione ordinaria",
                "Manutenzione straordinaria",
            ]
        ),
    )
    outcome = fields.Boolean(required=True)
    note = fields.String(
        load_default=None,
        allow_none=True,
        validate=validate.Length(max=500),
        validate=safe_string,
    )


maintenance_schema = MaintenanceSchema()


class MaintenanceResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}/<int:id_>"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def get(self, id_: int, identity: Dict[str, Any]) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "maintenance id must be positive integer."},
                STATUS_CODES["bad_request"],
            )

        maintenance = Maintenance.query.get(id_)
        if maintenance is None:
            return create_response(
                {"error": "no resource found with the specified id"},
                STATUS_CODES["not_found"],
            )

        log(
            message=f"User {identity} fetched maintenance with id {id_}",
            level="INFO",
            message_id="CTRLGET",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "maintenance_id": id_,
            },
        )
        return create_response(maintenance.to_dict(), STATUS_CODES["ok"])

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def patch(self, id_: int, identity: Dict[str, Any]) -> Response:
        try:
            data: Dict[str, Any] = maintenance_schema.load(
                request.get_json(), partial=True
            )
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        maintenance = Maintenance.query.get(id_)
        if maintenance is None:
            return create_response(
                {"error": "specified maintenance does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if "hydrant_id" in data and Hydrant.query.get(data["hydrant_id"]) is None:
            return create_response(
                {"error": "specified hydrant does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if (
            "user_email" in data
            and User.query.filter_by(email=data["user_email"]).first() is None
        ):
            return create_response(
                {"error": "specified user does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        if "hydrant_id" in data:
            maintenance.hydrant_id = data["hydrant_id"]
        if "user_email" in data:
            maintenance.user_email = data["user_email"]
        if "maintenance_timestamp" in data:
            maintenance.maintenance_timestamp = data["maintenance_timestamp"]
        if "type" in data:
            maintenance.type = data["type"]
        if "outcome" in data:
            maintenance.outcome = data["outcome"]
        if "note" in data:
            maintenance.note = data["note"]

        db.session.commit()
        log(
            message=f"User {identity} updated maintenance with id {id_}",
            level="INFO",
            message_id="CTRLPATCH",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "maintenance_id": id_,
            },
        )
        return create_response(
            {
                "outcome": "successfully updated maintenance",
                "location": get_hateos_location_string(bp_name=BP_NAME, id_=id_),
            },
            STATUS_CODES["ok"],
        )

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def delete(self, id_: int, identity: Dict[str, Any]) -> Response:
        if id_ <= 0:
            return create_response(
                {"error": "id_ must be positive integer."}, STATUS_CODES["bad_request"]
            )

        maintenance = Maintenance.query.get(id_)
        if maintenance is None:
            return create_response(
                {"error": "specified resource does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        db.session.delete(maintenance)
        db.session.commit()
        log(
            message=f"User {identity} deleted maintenance with id {id_}",
            level="INFO",
            message_id="CTRLDEL",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "maintenance_id": id_,
            },
        )
        return create_response(
            {"outcome": "successfully deleted maintenance"}, STATUS_CODES["ok"]
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


class MaintenancePostResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def post(self, identity: Dict[str, Any]) -> Response:
        try:
            data: Dict[str, Any] = maintenance_schema.load(request.get_json())
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        if Hydrant.query.get(data["hydrant_id"]) is None:
            return create_response(
                {"error": "specified hydrant does not exist in the database"},
                STATUS_CODES["not_found"],
            )
        if User.query.filter_by(email=data["user_email"]).first() is None:
            return create_response(
                {"error": "specified user does not exist in the database"},
                STATUS_CODES["not_found"],
            )

        new_maintenance = Maintenance(
            hydrant_id=data["hydrant_id"],
            user_email=data["user_email"],
            maintenance_timestamp=data["maintenance_timestamp"],
            type=data["type"],
            outcome=data["outcome"],
            note=data.get("note"),
        )
        db.session.add(new_maintenance)
        db.session.commit()

        log(
            message=f"User {identity} created maintenance with id_ {new_maintenance.maintenance_id}",
            level="INFO",
            message_id="CTRLPOST",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "maintenance_id": new_maintenance.maintenance_id,
            },
        )
        return create_response(
            {
                "outcome": "successfully created new maintenance",
                "location": get_hateos_location_string(
                    bp_name=BP_NAME, id_=new_maintenance.maintenance_id
                ),
            },
            STATUS_CODES["created"],
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


api.add_resource(MaintenanceResource, *MaintenanceResource.ENDPOINT_PATHS)
api.add_resource(MaintenancePostResource, *MaintenancePostResource.ENDPOINT_PATHS)
