"""
User blueprint backed by the user database table.
"""

from base64 import urlsafe_b64encode as base64_urlsafe_b64encode
from os import urandom as os_urandom
from os.path import basename as os_path_basename
from re import IGNORECASE as re_IGNORECASE
from re import search as re_search

from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from flask import Blueprint, Response, request
from flask_restful import Resource
from marshmallow import EXCLUDE, ValidationError, fields
from requests import post as requests_post
from requests.exceptions import RequestException

from api_server import ma, limiter, get_rate_limit
from configs.api_config import (
    AUTH_API_VERSION,
    AUTH_SERVER_HOST,
    AUTH_SERVER_PORT,
    IS_AUTH_SERVER_SSL,
    LOGIN_AVAILABLE_THROUGH_API,
    PBKDF2HMAC_SETTINGS,
    STATUS_CODES,
)
from models import User, db
from api_server import api
from .blueprints_utils import (
    create_response,
    get_hateos_location_string,
    handle_options_request,
    log,
    jwt_validation_required,
    safe_string,
)

# Define blueprint name constant based on file name
BP_NAME: str = os_path_basename(__file__).replace("_bp.py", "")

# Initialize blueprint object
user_bp = Blueprint(BP_NAME, __name__)


class UserSchema(ma.Schema):
    """
    Marshmallow schema for validating and deserializing input data for User resources.
    Contains validation rules for each field and specifies that unknown fields in the input should be rejected with an error.
    The ID field is not included since it's auto-generated by the database and should not be provided in input data, providing it in the input will result in a validation error.
    This approach also provides protection against overposting/mass assignment vulnerabilities, ensuring that clients cannot set fields that they are not supposed to.
    """

    class Meta:
        unknown = RAISE  # additional fields in the input will be rejected with an error

    # no field for user_id since it's auto-generated by the database and should not be provided in input data
    email = fields.Email(required=True)
    first_name = fields.String(required=True, validate=safe_string)
    last_name = fields.String(required=True, validate=safe_string)
    password = fields.String(required=True)
    must_change_password = fields.Boolean(load_default=True)


user_schema = UserSchema()


def hash_password(password: str) -> str:
    salt = os_urandom(16)
    kdf = PBKDF2HMAC(
        algorithm=PBKDF2HMAC_SETTINGS["algorithm"],
        length=PBKDF2HMAC_SETTINGS["length"],
        salt=salt,
        iterations=PBKDF2HMAC_SETTINGS["iterations"],
        backend=PBKDF2HMAC_SETTINGS["backend"],
    )
    hashed_password = base64_urlsafe_b64encode(kdf.derive(password.encode("utf-8")))
    return f"{base64_urlsafe_b64encode(salt).decode('utf-8')}:{hashed_password.decode('utf-8')}"


class UserResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}/<string:email>"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def get(self, email, identity) -> Response:
        user = User.query.filter_by(email=email).first()
        if user is None:
            return create_response(
                {"error": "user not found"}, STATUS_CODES["not_found"]
            )

        log(
            message=f"User {identity} fetched user {email} data",
            level="INFO",
            message_id="USRGET",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "requester": identity,
                "target_user": email,
            },
        )
        return create_response(user.to_dict(), STATUS_CODES["ok"])

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def patch(self, email, identity) -> Response:
        try:
            data = user_schema.load(request.get_json(), partial=True)
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        user = User.query.filter_by(email=email).first()
        if user is None:
            return create_response(
                {"error": "user not found"}, STATUS_CODES["not_found"]
            )

        if "password" in data:
            user.password = hash_password(data["password"])
        if "first_name" in data:
            user.first_name = data["first_name"]
        if "last_name" in data:
            user.last_name = data["last_name"]
        if "must_change_password" in data:
            user.must_change_password = data["must_change_password"]

        db.session.commit()
        log(
            message=f"User {identity} updated user {email}",
            level="INFO",
            message_id="USRPATCH",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "updater": identity,
                "updated_user": email,
            },
        )
        return create_response({"success": f"User {email} updated"}, STATUS_CODES["ok"])

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def delete(self, email, identity) -> Response:
        user = User.query.filter_by(email=email).first()
        if user is None:
            return create_response(
                {"error": "user not found with provided email"},
                STATUS_CODES["not_found"],
            )

        db.session.delete(user)
        db.session.commit()
        log(
            message=f"User {email} deleted user {identity}",
            level="INFO",
            message_id="USRDEL",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "deleter": email,
                "deleted_user": identity,
            },
        )
        return create_response({"success": f"User {email} deleted"}, STATUS_CODES["ok"])

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


class UserPostResource(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}"]

    @jwt_validation_required()
    @limiter.limit(lambda: get_rate_limit("default"))
    def post(self, identity) -> Response:
        try:
            data = user_schema.load(request.get_json())
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        if User.query.filter_by(email=data["email"]).count() > 0:
            return create_response(
                {"error": "user with provided email already exists"},
                STATUS_CODES["conflict"],
            )

        new_user = User(
            email=data["email"],
            first_name=data["first_name"],
            last_name=data["last_name"],
            password=hash_password(data["password"]),
            must_change_password=data.get("must_change_password", True),
        )
        db.session.add(new_user)
        db.session.commit()

        log(
            message=f"User {identity} created user {data['email']}",
            level="INFO",
            message_id="USRPOST",
            sd_tags={
                "endpoint": request.path,
                "method": request.method,
                "identity": identity,
                "email": data["email"],
            },
        )
        return create_response(
            {
                "outcome": f"User {data['email']} created",
                "location": get_hateos_location_string(
                    bp_name=BP_NAME, id_=data["email"]
                ),
            },
            STATUS_CODES["created"],
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


class UserLoginSchema(ma.Schema):
    email = fields.Email(required=True)
    password = fields.String(required=True)


user_login_schema = UserLoginSchema()


class UserLogin(Resource):
    ENDPOINT_PATHS = [f"/{BP_NAME}/auth/login"]

    @limiter.limit(lambda: get_rate_limit("strict"))
    def post(self) -> Response:
        if not LOGIN_AVAILABLE_THROUGH_API:
            return create_response(
                {
                    "error": "login not available through API server. Please contact authentication service directly"
                },
                STATUS_CODES["forbidden"],
            )

        try:
            data = user_login_schema.load(request.get_json())
        except ValidationError as err:
            return create_response({"error": err.messages}, STATUS_CODES["bad_request"])

        scheme = "https" if IS_AUTH_SERVER_SSL else "http"
        auth_url = f"{scheme}://{AUTH_SERVER_HOST}:{AUTH_SERVER_PORT}/auth/{AUTH_API_VERSION}/login"
        try:
            response = requests_post(auth_url, json=data, timeout=10)
        except RequestException as ex:
            log(
                message=f"Authentication service unavailable: {str(ex)}",
                level="ERROR",
                message_id="AUTHSRVUNAVAIL",
                sd_tags={"endpoint": request.path, "method": request.method},
            )
            return create_response(
                {"error": "authentication service unavailable"},
                STATUS_CODES["service_unavailable"],
            )

        if response.status_code == STATUS_CODES["ok"]:
            return create_response(response.json(), STATUS_CODES["ok"])

        if response.status_code == STATUS_CODES["unauthorized"]:
            log(
                message=f"User login failed for {data.get('email')}",
                level="WARNING",
                message_id="LOGINFAIL",
                sd_tags={"endpoint": request.path, "method": request.method},
            )
            return create_response(
                {"error": "Invalid credentials"}, STATUS_CODES["unauthorized"]
            )

        return create_response(
            {"error": "authentication service error"}, response.status_code
        )

    @jwt_validation_required()
    def options(self) -> Response:
        return handle_options_request(resource_class=self)


api.add_resource(UserResource, *UserResource.ENDPOINT_PATHS)
api.add_resource(UserPostResource, *UserPostResource.ENDPOINT_PATHS)
api.add_resource(UserLogin, *UserLogin.ENDPOINT_PATHS)
